/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'personality' : IDL.Null,
  'desire' : IDL.Null,
  'dream' : IDL.Null,
});
export const Item = IDL.Record({
  'id' : IDL.Nat,
  'existentialPrice' : IDL.Text,
  'name' : IDL.Text,
  'shortDescription' : IDL.Text,
  'category' : Category,
  'longDescription' : IDL.Text,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'themeTag' : IDL.Text,
  'excerpt' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
  'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getItemById' : IDL.Func([IDL.Nat], [Item], ['query']),
  'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(Item)], ['query']),
  'getJournalEntryById' : IDL.Func([IDL.Nat], [JournalEntry], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'personality' : IDL.Null,
    'desire' : IDL.Null,
    'dream' : IDL.Null,
  });
  const Item = IDL.Record({
    'id' : IDL.Nat,
    'existentialPrice' : IDL.Text,
    'name' : IDL.Text,
    'shortDescription' : IDL.Text,
    'category' : Category,
    'longDescription' : IDL.Text,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'themeTag' : IDL.Text,
    'excerpt' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllItems' : IDL.Func([], [IDL.Vec(Item)], ['query']),
    'getAllJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getItemById' : IDL.Func([IDL.Nat], [Item], ['query']),
    'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(Item)], ['query']),
    'getJournalEntryById' : IDL.Func([IDL.Nat], [JournalEntry], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };